# Generated by Django 4.2.2 on 2024-03-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageVolumeDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptCode', models.CharField(max_length=50)),
                ('timeCode', models.IntegerField()),
                ('averageVolume', models.FloatField()),
                ('lastDayVolume', models.IntegerField()),
                ('percentChange', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FnO_Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptCode', models.CharField(max_length=50)),
            ],
        ),
    ]
