# Generated by Django 4.2.2 on 2024-03-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_average_volume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FnO_Scripts',
            new_name='bluechips',
        ),
    ]
