# Generated by Django 4.2.2 on 2024-03-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_average_volume', '0002_rename_fno_scripts_bluechips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bluechips',
            new_name='bluechip',
        ),
    ]
